---
ansible-navigator:
  # Execution Environment Settings
  execution-environment:
    container-engine: podman
    enabled: true
    # The standard upstream image containing Core + Common Collections
    image: quay.io/ansible/creator-ee:latest
    pull:
      policy: missing

  # User Interface
  editor:
    command: nano  # Change to 'vim' or 'code' if you prefer
    console: true

  # Logging and Artifacts
  logging:
    level: info
    file: ./ansible-logs/ansible-navigator.log

  playbook-artifact:
    enable: true
    save-as: "{playbook_name}-artifact-{time_stamp}.json"

  # General settings
  mode: interactive

